### PR TITLE
Update build scripts to use system-wide S-lang

### PR DESCRIPTION
**Pull request by vitalyster**
apt-get install libslang2-dev || yum install slang-devel

### CODE REVIEW

**Comment by 5HT** [comment]
I have problem after upgrading: maxim@rigdzin:~/synrc/pie/deps/eslang$ ./demo.sh
Erlang R16B01 (erts-5.10.2) [source] [64-bit] [smp:4:4] [async-threads:100] [hipe] [kernel-poll:false]

"Failed to open driver: undefined symbol: SLang_Input_Buffer_Len
{"init terminating in do_boot",{nodriver,{open_error,-10}}}

**Comment by Zabrane** [comment]
Same here.

$ ./demo.sh 
Erlang R15B01 (erts-5.9.1) [source] [64-bit] [smp:4:4] [async-threads:100] [hipe] [kernel-poll:false]

Failed to open driver: undefined symbol: SLang_TT_Baud_Rate

=INFO REPORT==== 12-Oct-2013::23:39:18 ===
Path: "/home/eslang/priv"
{"init terminating in do_boot",{nodriver,{open_error,-10}}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

**Comment by 5HT** [comment]
sudo apt-get install libslang2-pic

**Comment by Zabrane** [comment]
What about Fedora?

**Comment by 5HT** [comment]
Don't know. Maybe libslang2-devel-static ?
You need something to link with -fPIC

**Comment by vitalyster** [comment]
yum install slang-static

**Pull request merged**
